
getwd()

library(readxl)

#load libraries tidyverse and simple features
library(tidyverse)
library(sf)

#import LQAS dataset
data<- read_excel("data.xlsx")

#load dataset
names(data)
#all_countries <- read_rds("global.ctry.rds")
#all_provinces <- read_rds("global.prov.rds")
#all_districts <- read_rds("global.dist.rds")

#defines variables
Rnd<-"Rnd1"
Annee<-2022
Response_code <- "GNBnOPV" ##### added response code and response in the select
#' function to show LQAS result 
#' @description to show in the map by Admin1 or Admin2  
Show_lqas_result <- function(data, all_countries, all_provinces, all_districts,Responce_Code,Rnd,Annee){
  #filter afro countries and provinces
  country_layer <-all_countries |>
    filter(WHO_REGION == "AFRO")
  province_layer <-all_provinces |>
    filter(WHO_REGION == "AFRO")
  district_layer <-all_districts |>
    filter(WHO_REGION == "AFRO")
  
  #LQAS level of performance 
  LQAS  <- data |> 
    select(Country, Region ,roundNumber,Performance,Start_date, District, Response) |> ##### added district and response
    mutate(Hight = ifelse(Performance == "Hight", 1, 0),
           Moderate=ifelse(Performance == "Moderate", 1, 0),
           Poor=ifelse(Performance == "Poor", 1, 0),
           Very_poor=ifelse(Performance == "Very_poor", 1, 0),
           Year=year(Start_date),
           Region = str_to_upper(Region) ##### As some Region were not in capital case, i converted all the table so that the join will match
           ) |>
    filter(roundNumber==Rnd, Year==Annee, Response==Response_code) |> 
    group_by(Country,Region,District) |>
    rowwise() |> 
    summarise( ##### changed summarise_at by summarise
      Hight = mean(Hight, na.rm = T), 
      Moderate = mean(Moderate, na.rm = T), 
      Poor = mean(Poor, na.rm = T), 
      Very_poor = mean(Very_poor, na.rm = T))
  #join the spatial layer of provinces
  LQAS_Performance <- left_join(LQAS, province_layer, ##### changed the X to be the LQAS file and Y to be the province
                                by=c("Country" = "ADM0_NAME", "Region" = "ADM1_NAME")) |> ##### changed country with Country (C in upper case)
                                                                                          ##### changed WHO_CODE with ADM0_NAME
    filter(Hight != "NA",Moderate!="NA",Poor!="NA",Very_poor!="NA") ##### changer Very_ppoor with Very_poor
    
  #plot the result of the analysis, 
  plot8 <- ##### Added plot8, where the plot generated by ggplot will be stored
    ggplot() +
    #load country layers with no fill
    geom_sf(data = country_layer, fill = NA) +
    #load province layer and fill by performance level
    geom_sf(data = LQAS_Performance, aes(fill = Hight, geometry = SHAPE)) + ##### used one column at a time, and specified the geometry column for mapping
    scale_fill_gradient(low = "green", high = "red", name = "Hight") + ##### create a gradient fill to color the region based on performance
    #add the title and sub title on the map
    labs(fill=paste0("#", Rnd),
         title= "LQAS",
         subtitle= paste0("Result from the most recent two SIA rounds", Rnd, 
                          " in ", Annee ))+
    theme_bw()
  
  ggsave("GBT.png", plot = plot8, width = 8, height = 8, bg = "white")
  
}

Show_lqas_result(data = data, all_countries = all_countries, all_provinces = all_provinces, 
                 all_districts = all_districts, Responce_Code = "Rnd1", Rnd = "Rnd1", Annee = 2024) #run the function with values
